// MARK: - WhisperLanguage

public struct WhisperLanguage: RawRepresentable, Hashable, Sendable, Codable {
  public var rawValue: String

  public init(rawValue: String) {
    self.rawValue = rawValue
  }
}

// MARK: - CactusPromptRepresentable Conformance

extension WhisperLanguage: CactusPromptRepresentable {
  public var promptContent: CactusPromptContent {
    CactusPromptContent(text: "<|\(self.rawValue)|>")
  }
}

// MARK: - Supported Languages

extension WhisperLanguage {
  public static let afrikaans = Self(rawValue: "af")
  public static let albanian = Self(rawValue: "sq")
  public static let amharic = Self(rawValue: "am")
  public static let arabic = Self(rawValue: "ar")
  public static let armenian = Self(rawValue: "hy")
  public static let assamese = Self(rawValue: "as")
  public static let azerbaijani = Self(rawValue: "az")
  public static let bashkir = Self(rawValue: "ba")
  public static let belarusian = Self(rawValue: "be")
  public static let bengali = Self(rawValue: "bn")
  public static let bosnian = Self(rawValue: "bs")
  public static let breton = Self(rawValue: "br")
  public static let bulgarian = Self(rawValue: "bg")
  public static let catalan = Self(rawValue: "ca")
  public static let chinese = Self(rawValue: "zh")
  public static let croatian = Self(rawValue: "hr")
  public static let czech = Self(rawValue: "cs")
  public static let danish = Self(rawValue: "da")
  public static let dutch = Self(rawValue: "nl")
  public static let english = Self(rawValue: "en")
  public static let esperanto = Self(rawValue: "eo")
  public static let estonian = Self(rawValue: "et")
  public static let faroese = Self(rawValue: "fo")
  public static let finnish = Self(rawValue: "fi")
  public static let french = Self(rawValue: "fr")
  public static let galician = Self(rawValue: "gl")
  public static let georgian = Self(rawValue: "ka")
  public static let german = Self(rawValue: "de")
  public static let greek = Self(rawValue: "el")
  public static let gujarati = Self(rawValue: "gu")
  public static let haitianCreole = Self(rawValue: "ht")
  public static let hausa = Self(rawValue: "ha")
  public static let hawaiian = Self(rawValue: "haw")
  public static let hebrew = Self(rawValue: "he")
  public static let hindi = Self(rawValue: "hi")
  public static let hungarian = Self(rawValue: "hu")
  public static let icelandic = Self(rawValue: "is")
  public static let indonesian = Self(rawValue: "id")
  public static let irish = Self(rawValue: "ga")
  public static let italian = Self(rawValue: "it")
  public static let japanese = Self(rawValue: "ja")
  public static let javanese = Self(rawValue: "jw")
  public static let kannada = Self(rawValue: "kn")
  public static let kazakh = Self(rawValue: "kk")
  public static let khmer = Self(rawValue: "km")
  public static let korean = Self(rawValue: "ko")
  public static let lao = Self(rawValue: "lo")
  public static let latin = Self(rawValue: "la")
  public static let latvian = Self(rawValue: "lv")
  public static let lingala = Self(rawValue: "ln")
  public static let lithuanian = Self(rawValue: "lt")
  public static let luxembourgish = Self(rawValue: "lb")
  public static let macedonian = Self(rawValue: "mk")
  public static let malagasy = Self(rawValue: "mg")
  public static let malay = Self(rawValue: "ms")
  public static let malayalam = Self(rawValue: "ml")
  public static let maltese = Self(rawValue: "mt")
  public static let maori = Self(rawValue: "mi")
  public static let marathi = Self(rawValue: "mr")
  public static let mongolian = Self(rawValue: "mn")
  public static let nepali = Self(rawValue: "ne")
  public static let norwegian = Self(rawValue: "no")
  public static let norwegianNynorsk = Self(rawValue: "nn")
  public static let occitan = Self(rawValue: "oc")
  public static let pashto = Self(rawValue: "ps")
  public static let persian = Self(rawValue: "fa")
  public static let polish = Self(rawValue: "pl")
  public static let portuguese = Self(rawValue: "pt")
  public static let punjabi = Self(rawValue: "pa")
  public static let romanian = Self(rawValue: "ro")
  public static let russian = Self(rawValue: "ru")
  public static let sanskrit = Self(rawValue: "sa")
  public static let serbian = Self(rawValue: "sr")
  public static let shona = Self(rawValue: "sn")
  public static let sindhi = Self(rawValue: "sd")
  public static let sinhala = Self(rawValue: "si")
  public static let slovak = Self(rawValue: "sk")
  public static let slovenian = Self(rawValue: "sl")
  public static let somali = Self(rawValue: "so")
  public static let spanish = Self(rawValue: "es")
  public static let sundanese = Self(rawValue: "su")
  public static let swahili = Self(rawValue: "sw")
  public static let swedish = Self(rawValue: "sv")
  public static let tagalog = Self(rawValue: "tl")
  public static let tajik = Self(rawValue: "tg")
  public static let tamil = Self(rawValue: "ta")
  public static let tatar = Self(rawValue: "tt")
  public static let telugu = Self(rawValue: "te")
  public static let thai = Self(rawValue: "th")
  public static let tibetan = Self(rawValue: "bo")
  public static let turkish = Self(rawValue: "tr")
  public static let turkmen = Self(rawValue: "tk")
  public static let ukrainian = Self(rawValue: "uk")
  public static let urdu = Self(rawValue: "ur")
  public static let uzbek = Self(rawValue: "uz")
  public static let vietnamese = Self(rawValue: "vi")
  public static let welsh = Self(rawValue: "cy")
  public static let yiddish = Self(rawValue: "yi")
  public static let yoruba = Self(rawValue: "yo")
  public static let zulu = Self(rawValue: "zu")
}
